title: Pustaka Isa
tagline: Pustaka Isa
description: Pustaka Pribadi Isa Mujahid Islam
url: https://pustaka.isa.web.id
author: Isa Mujahid Islam
google_analytics: 
theme: jekyll-theme-slate
lang: in
twitter:
  username: benbalter
  card: 152m1
logo: /assets/images/logo.png
social:
  name: Isa Mujahid Islam
  links:
    - https://twitter.com/152m1
    - https://www.linkedin.com/in/isa-mujahid-islam-b712b740/
    - https://github.com/isandroid
google_site_verification: axYmCzFKvYf0k574bQ6rSFmv5xuDDmVMjU7oOOTr20M
google_analytics: G-G2Y182KL54
plugins:
  - jekyll-sitemap
  - jekyll-feed
feed:
  path: atom.xml